(function () {
  const { useState } = React;
  const H = window.HuddleV2;
  const { arr, num, slug } = H.helpers;
  const LOGO = 'https://talimg1.b8cdn.com/wp-content/themes/talentera-2018/images/new-design/Talentera-ATS-white-logo.svg';
  H.StatePanel = ({ loading, error, retry }) => <div className="state"><div className="state-card">{loading ? <><span className="spinner"/><b>Loading Talentera Huddle…</b></> : <><b>Dashboard data could not be loaded</b><p>{error}</p><button onClick={retry}>Try again</button></>}</div></div>;
  const NavLabel = ({ children }) => <div className="nav-label">{children}</div>;
  const Nav = ({ active, icon, alert, onClick, children }) => <button className={`nav ${active ? 'active' : ''}`} onClick={onClick}><i>{icon}</i><span>{children}</span>{alert && <em>!</em>}</button>;
  H.Sidebar = function Sidebar({ data, page, go, open, close }) { return <><aside className={open ? 'open' : ''}><div className="brand"><img src={LOGO}/><small>Talentera Huddle</small></div><nav><NavLabel>Main</NavLabel><Nav active={page === 'team'} icon="▦" onClick={() => go('team')}>Acquisition</Nav><Nav active={page === 'financial'} icon="$" onClick={() => go('financial')}>Financial</Nav><NavLabel>External</NavLabel><a className="nav" href="https://amohamed-alt.github.io/talentera-retention/" target="_blank"><i>◉</i><span>Retention</span><em>↗</em></a><a className="nav" href="#" onClick={event => event.preventDefault()}><i>↗</i><span>P&amp;L</span><em>↗</em></a><NavLabel>Reps</NavLabel>{arr(data.repData).map(rep => <Nav key={rep.name} active={page === `rep/${slug(rep.name)}`} icon={<H.Avatar rep={rep} small/>} alert={rep.type !== 'view' && (num(rep.connRateYest) < 30 || arr(rep.stuck).length || arr(rep.cold).length > 3)} onClick={() => go(`rep/${slug(rep.name)}`)}>{rep.name}</Nav>)}</nav><div className="user"><b>SM</b><span><strong>Sales Manager</strong><small>Admin · Riyadh</small></span></div></aside>{open && <button className="overlay" onClick={close}/>}</>; };
  H.Tabs = ({ reps, page, go }) => <div className="tabs"><button className={page === 'team' ? 'active' : ''} onClick={() => go('team')}>⌂ Team Overview</button><button className={page === 'financial' ? 'active' : ''} onClick={() => go('financial')}>$ Financial</button>{reps.map(rep => <button key={rep.name} className={page === `rep/${slug(rep.name)}` ? 'active' : ''} onClick={() => go(`rep/${slug(rep.name)}`)}><i style={{ background: rep.color || '#13a466' }}/> {rep.name.split(' ')[0]}</button>)}</div>;
  H.Header = function Header({ title, subtitle, data, loading, refresh, go, openRows, menu }) { const [query, setQuery] = useState(''); const search = () => { const q = query.trim().toLowerCase(); if (!q) return; const rows = [...arr(data.outreachCoverage?.contacts?.notContactedList), ...arr(data.repData).flatMap(rep => arr(rep.topDeals).map(row => ({ ...row, ownerName: rep.name }))), ...arr(data.closedWon), ...arr(data.closedLost)].filter(row => JSON.stringify(row).toLowerCase().includes(q)); openRows(`Search results (${rows.length})`, q, rows, 'No matching acquisition records.'); }; return <><header><button className="icon mobile" onClick={menu}>☰</button><div className="search"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} onKeyDown={event => event.key === 'Enter' && search()} placeholder="Search lead, deal, account, rep…"/><kbd>⌘ F</kbd></div><div className="actions"><button className="icon" onClick={() => go('team')}>↗</button><button className="icon" onClick={refresh}>⟳</button><span className="live"><i/> Live · HubSpot</span><button className="primary" onClick={refresh}>{loading ? '⟳' : '↻'} Refresh Data</button></div></header><section className="hero"><div><h1>{title}</h1><p>{subtitle}</p></div><div><button className="primary" onClick={() => go('financial')}>+ Open Financial Tab</button><button className="outline" onClick={() => go('team')}>Open Data</button></div></section></>; };
})();
